#!/bin/bash
# Configure passwordless sudo for deployment user
# Run this script on your Ubuntu server as root or with sudo

set -e

if [ "$EUID" -ne 0 ]; then 
  echo "Please run as root or with sudo"
  exit 1
fi

# Get the current user (or use the first argument)
DEPLOY_USER="${1:-$SUDO_USER}"

if [ -z "$DEPLOY_USER" ]; then
  echo "Usage: sudo $0 [username]"
  echo "Or run as: sudo -u root $0"
  exit 1
fi

echo "Configuring passwordless sudo for user: $DEPLOY_USER"

# Create sudoers.d file for the deployment user
SUDOERS_FILE="/etc/sudoers.d/dsa-table-deploy"

cat > "$SUDOERS_FILE" <<'EOF'
# Passwordless sudo for DSA Table deployment
# User: DEPLOY_USER_PLACEHOLDER
# Generated by configure-passwordless-sudo.sh

# Allow specific commands needed for deployment
# Note: Commands are allowed with any arguments for flexibility
# This is reasonably secure as we're only allowing specific commands
DEPLOY_USER_PLACEHOLDER ALL=(ALL) NOPASSWD: /bin/mkdir
DEPLOY_USER_PLACEHOLDER ALL=(ALL) NOPASSWD: /bin/cp
DEPLOY_USER_PLACEHOLDER ALL=(ALL) NOPASSWD: /bin/mv
DEPLOY_USER_PLACEHOLDER ALL=(ALL) NOPASSWD: /bin/chown
DEPLOY_USER_PLACEHOLDER ALL=(ALL) NOPASSWD: /bin/chmod
DEPLOY_USER_PLACEHOLDER ALL=(ALL) NOPASSWD: /bin/tar
DEPLOY_USER_PLACEHOLDER ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart dsa-table-backend.service
DEPLOY_USER_PLACEHOLDER ALL=(ALL) NOPASSWD: /usr/bin/systemctl status dsa-table-backend.service
DEPLOY_USER_PLACEHOLDER ALL=(ALL) NOPASSWD: /usr/bin/systemctl reload apache2
DEPLOY_USER_PLACEHOLDER ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart apache2
EOF

# Replace placeholder with actual username
sed -i "s/DEPLOY_USER_PLACEHOLDER/$DEPLOY_USER/g" "$SUDOERS_FILE"

# Set proper permissions
chmod 0440 "$SUDOERS_FILE"

# Verify syntax
visudo -c -f "$SUDOERS_FILE"

echo ""
echo "✅ Passwordless sudo configured successfully!"
echo ""
echo "The following commands are now allowed without password:"
echo "  - Managing /opt/dsa-table-backend directory"
echo "  - Managing /var/www/html/dsa-table directory"
echo "  - Restarting dsa-table-backend.service"
echo "  - Reloading/restarting Apache"
echo ""
echo "Test with: sudo -n true"
echo "If it returns without error, passwordless sudo is working."

