#!/bin/bash
# Alternative: Configure passwordless sudo for ALL commands (less secure but simpler)
# Use this only if you trust the deployment user completely
# Run this script on your Ubuntu server as root or with sudo

set -e

if [ "$EUID" -ne 0 ]; then 
  echo "Please run as root or with sudo"
  exit 1
fi

# Get the current user (or use the first argument)
DEPLOY_USER="${1:-$SUDO_USER}"

if [ -z "$DEPLOY_USER" ]; then
  echo "Usage: sudo $0 [username]"
  echo "Or run as: sudo -u root $0"
  exit 1
fi

echo "⚠️  WARNING: This will allow $DEPLOY_USER to run ALL sudo commands without password!"
echo "This is less secure but simpler. Press Ctrl+C to cancel, or Enter to continue..."
read

echo "Configuring passwordless sudo for user: $DEPLOY_USER"

# Create sudoers.d file for the deployment user
SUDOERS_FILE="/etc/sudoers.d/dsa-table-deploy-full"

cat > "$SUDOERS_FILE" <<EOF
# Passwordless sudo for DSA Table deployment (FULL ACCESS)
# User: $DEPLOY_USER
# WARNING: This allows all sudo commands without password
# Generated by configure-sudo-alternative.sh

$DEPLOY_USER ALL=(ALL) NOPASSWD: ALL
EOF

# Set proper permissions
chmod 0440 "$SUDOERS_FILE"

# Verify syntax
visudo -c -f "$SUDOERS_FILE"

echo ""
echo "✅ Passwordless sudo configured successfully!"
echo ""
echo "⚠️  WARNING: $DEPLOY_USER can now run ALL sudo commands without password!"
echo ""
echo "Test with: sudo -n true"
echo "If it returns without error, passwordless sudo is working."

